apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: apache/causeway-app-helloworld
        ports:
        - containerPort: 80

