# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

server_ip = "192.168.56.110"
worker_ip = "192.168.56.111"

Vagrant.configure("2") do |config|
    # k3s Server Node
    config.vm.define "server" do |server|
        server.vm.box = "generic/debian12"
        server.vm.hostname = "agonelleS"

        server.vm.network "private_network", ip: server_ip

        server.vm.provider :virtualbox do |vb|
            vb.cpus = 1
            vb.memory = 1024
        end

#        server.vm.synced_folder "./shared", "/vagrant_shared"
        server.vm.provision "shell", inline: <<-SHELL
            # Update and install dependencies
            apt-get update -y
            apt-get install -y curl

            # Install K3s as a server

            #curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -
            #sleep 10
            #cp /var/lib/rancher/k3s/server/token /tmp/token
            #chmod 444 /tmp/token

            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - \
                --write-kubeconfig-mode '0644' \
                --node-ip #{server_ip}

            sleep 2
            sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/token
        SHELL
    end

    # k3s Worker Node
    config.vm.define "worker" do |worker|
        worker.vm.box = "generic/debian12"
        worker.vm.hostname = "esanchezSW"

        worker.vm.network "private_network", ip: worker_ip

        worker.vm.provider :virtualbox do |vb|
            vb.cpus = 1
            vb.memory = 1024
        end

#        worker.vm.synced_folder "./shared", "/vagrant_shared"
        worker.vm.provision "shell", inline: <<-SHELL
            # Update and install dependencies
            #apt-get update -y
            #apt-get install -y curl openssh-client sshpass

            #sshpass -p "vagrant" scp -o StrictHostKeyChecking=no vagrant@#{server_ip}:/var/lib/rancher/k3s/server/token /tmp/token

            # Install k3s as a worker and join the server
            #export K3S_TOKEN_FILE=/tmp/token
            #export K3S_URL=https://#{server_ip}:6443
            #curl -sfL https://get.k3s.io | sh -

            while [ ! -f /vagrant/token ]; do
              sleep 1
            done

            cp /vagrant/token /tmp/token
            rm /vagrant/token
            cat /tmp/token

            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" K3S_URL=https://#{server_ip}:6443 K3S_TOKEN=$(cat /tmp/token) sh -s - \
                --node-ip "#{worker_ip}"

        SHELL
    end
    config.vm.synced_folder ".", "/vagrant"
end




   # config.vm.box_version = "4.3.12"
    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for up192.168.0.1dates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # config.vm.box_check_update = false
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.33.10"
  
    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network "public_network"
  
    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"
  
    # Disable the default share of the current code directory. Doing this
    # provides improved isolation between the vagrant box and your host
    # by making sure your Vagrantfile isn't accessible to the vagrant box.
    # If you use this you may want to enable additional shared subfolders as
    # shown above.
    # config.vm.synced_folder ".", "/vagrant", disabled: true
  
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    # config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end
    #
    # View the documentation for the provider you are using for more
    # information on available options.
  
    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    # config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL
